import React, { useEffect, useState } from 'react';
import {
  ArrowLeft, Bell, Camera, ChevronRight, CircleHelp, CreditCard, Globe2,
  Info, LogOut, MapPin, MessageSquare, Moon, Package, Plus, ShieldCheck,
  Sun, Trash2, UserRound, WalletCards, X, Smartphone, Headphones,
} from 'lucide-react';
import { useTranslation } from 'react-i18next';
import packageJson from '../../../package.json';
import { useApp } from '../../context/AppContext';
import { supabase } from '../../lib/supabase';

const EMPTY_ADDRESS = { label: 'Casa', addressLine1: '', addressLine2: '', neighborhood: '', municipality: '', city: 'Luanda', province: 'Luanda', reference: '', latitude: null, longitude: null, location: null };
const PROFILE_VIEWS = new Set(['wallet', 'addresses', 'edit_profile', 'notifications', 'notification_preferences', 'language', 'theme', 'security', 'help', 'legal', 'about']);
const PEDEJA_WHATSAPP_NUMBER = (import.meta.env.VITE_PEDEJA_WHATSAPP_NUMBER || '').replace(/\\D/g, '');

function Row({ icon, title, detail, onClick, danger = false }) {
  return <button onClick={onClick} className={`w-full flex items-center gap-3 px-4 py-3.5 text-left border-b border-gray-100 last:border-0 hover:bg-gray-50 ${danger ? 'text-red-600' : 'text-gray-800'}`}><span className={`w-9 h-9 rounded-xl flex items-center justify-center ${danger ? 'bg-red-50' : 'bg-violet-50 text-violet-700'}`}>{React.createElement(icon, { size: 18 })}</span><span className="min-w-0 flex-1"><span className="block font-semibold text-sm">{title}</span>{detail && <span className="block text-xs text-gray-400 mt-0.5 truncate">{detail}</span>}</span><ChevronRight size={17} className="text-gray-300 shrink-0" /></button>;
}

function Section({ title, children }) {
  return <section className="mt-5"><h2 className="px-1 mb-2 text-[10px] tracking-[0.16em] uppercase font-black text-gray-400">{title}</h2><div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">{children}</div></section>;
}

function WalletCard({ onClick, balance = 0 }) {
  return <button onClick={onClick} className="w-full text-left rounded-[22px] bg-gradient-to-br from-[#5d36a6] via-[#34205f] to-[#21153d] text-white p-5 shadow-[0_18px_40px_rgba(52,32,95,0.25)] relative overflow-hidden">
    <div className="absolute -right-12 -top-16 w-48 h-48 rounded-full bg-white/10 blur-2xl" /><div className="absolute right-8 bottom-[-50px] w-40 h-40 rounded-full border border-white/10" />
    <div className="relative flex items-center justify-between"><span className="font-black tracking-[0.18em] text-xs">PEDEJÁ.</span><WalletCards size={19} className="text-violet-100" /></div>
    <div className="relative mt-7 flex items-end justify-between gap-4"><div><p className="text-[9px] uppercase tracking-[0.16em] text-violet-200 font-bold">Saldo</p><p className="text-3xl font-black mt-1">{Number(balance || 0).toLocaleString('pt-AO')} Kz</p></div><ChevronRight size={18} className="text-white/70 mb-1" /></div>
  </button>;
}
function WalletDetail({ onBack }) {
  const [balance,setBalance]=useState(0); const [movements,setMovements]=useState([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{let cancelled=false;(async()=>{const [{data:snapshot},{data:rows}]=await Promise.all([supabase.rpc('customer_wallet_snapshot'),supabase.rpc('customer_wallet_movements',{p_limit:30})]);if(cancelled)return;setBalance(Number(snapshot?.[0]?.available_balance??snapshot?.available_balance??0));setMovements(Array.isArray(rows)?rows:[]);setLoading(false)})();return()=>{cancelled=true}},[]);
  return <div className="pb-24"><Header title="Carteira Pedejá" onBack={onBack}/><div className="p-4"><WalletCard onClick={()=>{}} balance={balance}/><div className="mt-5 bg-white rounded-2xl border border-gray-100 p-4"><div className="flex items-center gap-2"><WalletCards size={17} className="text-violet-700"/><h2 className="font-black">Movimentos</h2></div>{loading?<p className="py-8 text-center text-sm text-gray-400">A carregar...</p>:movements.length?<div className="mt-3 divide-y divide-gray-100">{movements.map((m,i)=><div key={m.id||m.created_at||i} className="py-3 flex justify-between gap-3"><div><p className="text-sm font-semibold">{m.description||m.transaction_type||'Movimento'}</p><p className="text-[10px] text-gray-400 mt-0.5">{m.created_at?new Date(m.created_at).toLocaleString('pt-AO'):''}</p></div><p className="font-black text-sm">{Number(m.amount??m.credit??0).toLocaleString('pt-AO')} Kz</p></div>)}</div>:<p className="py-8 text-center text-sm text-gray-400">Ainda não existem movimentos.</p>}</div></div></div>;
}
function Header({ title, onBack }) {
  return <div className="sticky top-0 z-20 bg-white/95 backdrop-blur border-b border-gray-100 px-4 py-3 flex items-center gap-3"><button onClick={onBack} className="p-2 -ml-2 rounded-full hover:bg-gray-100" aria-label="Voltar"><ArrowLeft size={20} /></button><h1 className="font-black text-gray-900">{title}</h1></div>;
}

function ProfileEditor({ userProfile, tempProfile, setTempProfile, onBack, onSave, profileUploading }) {
  const [message, setMessage] = useState('');
  const [savingIdentity, setSavingIdentity] = useState(false);
  const changedPhone = (tempProfile.phone || '') !== (userProfile.phone || '');
  const changedEmail = (tempProfile.email || '') !== (userProfile.email || '');
  const save = async () => {
    setSavingIdentity(true); setMessage('');
    const updates = {};
    if (changedPhone) updates.phone = tempProfile.phone;
    if (changedEmail) updates.email = tempProfile.email;
    if (Object.keys(updates).length) {
      const { error } = await supabase.auth.updateUser(updates);
      if (error) { setMessage(error.message || 'Não foi possível iniciar a verificação.'); setSavingIdentity(false); return; }
      setMessage('Enviámos uma verificação para os dados alterados. Confirma antes de usar o novo contacto.');
    }
    await onSave({ ...tempProfile, phone: userProfile.phone, email: userProfile.email });
    setSavingIdentity(false);
  };
  return <div className="pb-24"><Header title="Dados pessoais" onBack={onBack} /><div className="p-4"><div className="flex justify-center mb-6"><label htmlFor="profile-photo-input" className="w-24 h-24 bg-gray-100 rounded-full overflow-hidden relative cursor-pointer"><img src={tempProfile.image || `https://ui-avatars.com/api/?name=${encodeURIComponent(tempProfile.name || 'Pedejá')}&background=34205f&color=fff&size=96`} className="w-full h-full object-cover" alt="Foto de perfil" /><span className="absolute inset-0 bg-black/35 flex items-center justify-center text-white">{profileUploading ? <span className="w-5 h-5 border-2 border-white/40 border-t-white rounded-full animate-spin" /> : <Camera />}</span><input id="profile-photo-input" type="file" accept="image/*" className="hidden" onChange={event => { const file = event.target.files?.[0]; if (file) onSave({ ...tempProfile, _photoEvent: event }); }} disabled={profileUploading} /></label></div><div className="bg-white rounded-2xl border border-gray-100 p-4 space-y-4"><label className="block text-sm text-gray-500">Nome<input value={tempProfile.name || ''} onChange={event => setTempProfile({ ...tempProfile, name: event.target.value })} className="w-full mt-1 border rounded-xl px-3 py-3 text-gray-900" autoComplete="name" /></label><label className="block text-sm text-gray-500">Telefone<input value={tempProfile.phone || ''} onChange={event => setTempProfile({ ...tempProfile, phone: event.target.value })} className="w-full mt-1 border rounded-xl px-3 py-3 text-gray-900" autoComplete="tel" /></label><label className="block text-sm text-gray-500">Email<input value={tempProfile.email || ''} onChange={event => setTempProfile({ ...tempProfile, email: event.target.value })} className="w-full mt-1 border rounded-xl px-3 py-3 text-gray-900" autoComplete="email" /></label>{message && <p className="text-xs text-violet-700 bg-violet-50 rounded-xl p-3">{message}</p>}<button disabled={savingIdentity || profileUploading} onClick={save} className="w-full bg-violet-700 text-white py-3 rounded-xl font-bold disabled:opacity-50">{savingIdentity ? 'A guardar...' : 'Guardar alterações'}</button></div><p className="text-xs text-gray-400 mt-3">Alterações de telefone e email exigem confirmação através do Supabase Auth.</p></div></div>;
}

function Addresses({ userAddresses, newAddr, setNewAddr, handleAddAddress, handleDeleteAddress, getCurrentLocationForForm, onBack }) {
  const [adding, setAdding] = useState(false);
  const save = async () => { const ok = await handleAddAddress(newAddr); if (ok) { setNewAddr({ ...EMPTY_ADDRESS }); setAdding(false); } };
  return <div className="pb-24"><Header title="Moradas" onBack={onBack} /><div className="p-4"><p className="text-sm text-gray-500 mb-4">Moradas guardadas para Fome, Compras e Enviar Pacote.</p><div className="space-y-3">{userAddresses.map(address => <div key={address.id} className="bg-white rounded-2xl border border-gray-100 p-4 flex gap-3"><MapPin size={18} className="text-violet-700 mt-1 shrink-0" /><div className="min-w-0 flex-1"><p className="font-bold text-gray-900">{address.label}</p><p className="text-sm text-gray-600 mt-1">{address.address || 'Morada sem detalhes'}</p><p className="text-xs text-gray-400 mt-1">{address.location ? 'Localização pronta para entregas' : 'Localização ainda não resolvida'}</p></div><button onClick={() => handleDeleteAddress(address.id)} aria-label="Remover morada" className="p-2 text-red-500"><Trash2 size={16} /></button></div>)}{userAddresses.length === 0 && <div className="bg-white rounded-2xl border border-gray-100 p-8 text-center text-sm text-gray-400">Ainda não existem moradas guardadas.</div>}</div><button onClick={() => setAdding(value => !value)} className="w-full mt-4 py-3 rounded-xl bg-violet-700 text-white font-bold flex items-center justify-center gap-2"><Plus size={17} /> {adding ? 'Cancelar' : 'Adicionar morada'}</button>{adding && <div className="mt-4 bg-white rounded-2xl border border-gray-100 p-4 space-y-3"><select value={newAddr.label} onChange={event => setNewAddr({ ...newAddr, label: event.target.value })} className="w-full border rounded-xl p-3"><option>Casa</option><option>Trabalho</option><option>Escola</option><option>Outro</option></select><input value={newAddr.addressLine1} onChange={event => setNewAddr({ ...newAddr, addressLine1: event.target.value })} placeholder="Rua / Avenida e número" className="w-full border rounded-xl p-3" /><div className="grid grid-cols-2 gap-2"><input value={newAddr.neighborhood} onChange={event => setNewAddr({ ...newAddr, neighborhood: event.target.value })} placeholder="Bairro" className="w-full border rounded-xl p-3" /><input value={newAddr.municipality} onChange={event => setNewAddr({ ...newAddr, municipality: event.target.value })} placeholder="Município" className="w-full border rounded-xl p-3" /></div><input value={newAddr.reference} onChange={event => setNewAddr({ ...newAddr, reference: event.target.value })} placeholder="Referência" className="w-full border rounded-xl p-3" /><button onClick={getCurrentLocationForForm} className="w-full border border-violet-200 text-violet-700 rounded-xl py-3 font-semibold">Usar localização actual</button><button onClick={save} className="w-full bg-violet-700 text-white rounded-xl py-3 font-bold">Guardar morada</button></div>}</div></div>;
}

function Support({ currentUser, onBack }) {
  const [category,setCategory]=useState('Problema com a minha conta'); const [description,setDescription]=useState(''); const [message,setMessage]=useState('');
  const submit=async()=>{if(!description.trim())return setMessage('Descreve brevemente o que aconteceu.');if(!PEDEJA_WHATSAPP_NUMBER)return setMessage('O WhatsApp do Pedejá ainda não está configurado.');const {data,error}=await supabase.rpc('support_create_case',{p_subject_type:'CUSTOMER',p_subject_id:currentUser?.id,p_case_type:category,p_title:category,p_description:description.trim(),p_metadata:{channel:'whatsapp'},p_idempotency_key:`perfil-${currentUser?.id}-${Date.now()}`});if(error)return setMessage(error.message||'Não foi possível criar o pedido de suporte.');window.open(`https://wa.me/${PEDEJA_WHATSAPP_NUMBER}?text=${encodeURIComponent(`Olá Pedejá. Categoria: ${category}. ${description.trim()}`)}`,'_blank','noopener,noreferrer');setMessage('O WhatsApp foi aberto com o teu pedido.');setDescription('')};
  return <div className="pb-24"><Header title="Suporte" onBack={onBack}/><div className="p-4 space-y-4"><div className="bg-white rounded-2xl border border-gray-100 overflow-hidden"><div className="px-4 py-3 font-black">🆘 Ajuda</div><div className="grid grid-cols-3 border-t border-gray-100">{[['113','Polícia Nacional'],['112','Ambulância'],['115','Bombeiros']].map(([n,l])=><a key={n} href={`tel:${n}`} className="p-4 text-center border-r last:border-0 border-gray-100"><p className="font-black text-lg">{n}</p><p className="text-[10px] text-gray-500 mt-1">{l}</p></a>)}</div></div><div className="bg-white rounded-2xl border border-gray-100 p-4"><div className="flex items-center gap-2 font-black"><Headphones size={17}/> WhatsApp</div><div className="mt-4 space-y-3">{['Problema com um pedido','Problema com um pacote','Problema com pagamento','Problema com a minha conta','Outro assunto'].map(item=><button key={item} onClick={()=>setCategory(item)} className={`w-full text-left px-4 py-3 rounded-xl border text-sm ${category===item?'border-violet-500 bg-violet-50 text-violet-800 font-bold':'border-gray-200'}`}>{item}</button>)}<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4} placeholder="Descreve a tua questão..." className="w-full border rounded-xl p-3 text-sm"/>{message&&<p className="text-xs text-violet-700 bg-violet-50 rounded-xl p-3">{message}</p>}<button onClick={submit} className="w-full bg-violet-700 text-white py-3 rounded-xl font-bold">Abrir WhatsApp</button></div></div></div></div>;
}
export default function ProfileTab() {
  const { i18n } = useTranslation();
  const { userProfile,currentUser,profileSubView,setProfileSubView,userAddresses,newAddr,setNewAddr,handleAddAddress,handleDeleteAddress,getCurrentLocationForForm,tempProfile,setTempProfile,handleProfilePhotoChange,handleSaveProfile,profileUploading,handleLogout,setThemeMode,themeMode } = useApp();
  const actualUser=currentUser||{id:userProfile?.id}; const go=view=>setProfileSubView(view);
  const [deleteOpen,setDeleteOpen]=useState(false); const [deleteMessage,setDeleteMessage]=useState('');
  const [notif,setNotif]=useState({order_notifications:true,offer_notifications:true,payment_notifications:true,delivery_status_notifications:true}); const [notifLoading,setNotifLoading]=useState(false); const [notifMessage,setNotifMessage]=useState('');
  useEffect(()=>{if(profileSubView!=='notification_preferences'||!actualUser?.id)return;let cancelled=false;(async()=>{setNotifLoading(true);const {data,error}=await supabase.rpc('customer_notification_preferences');if(cancelled)return;if(!error&&data?.[0])setNotif(data[0]);setNotifLoading(false)})();return()=>{cancelled=true}},[profileSubView,actualUser?.id]);
  const saveNotif=async(next)=>{setNotif(next);const {error}=await supabase.rpc('customer_update_notification_preferences',{p_order:next.order_notifications,p_offer:next.offer_notifications,p_payment:next.payment_notifications,p_delivery_status:next.delivery_status_notifications});if(error)setNotifMessage(error.message||'Não foi possível guardar as preferências.');else setNotifMessage('Preferências guardadas.')};
  const requestDelete=async()=>{const {error}=await supabase.rpc('customer_request_account_deletion');if(error)return setDeleteMessage(error.message||'A conta não pode ser apagada neste momento.');await handleLogout()};
  const saveProfile=async values=>{if(values._photoEvent){await handleProfilePhotoChange(values._photoEvent);return}await handleSaveProfile(values);go('main')};

  if(profileSubView==='wallet')return <WalletDetail onBack={()=>go('main')}/>;
  if(profileSubView==='addresses')return <Addresses userAddresses={userAddresses} newAddr={newAddr} setNewAddr={setNewAddr} handleAddAddress={handleAddAddress} handleDeleteAddress={handleDeleteAddress} getCurrentLocationForForm={getCurrentLocationForForm} onBack={()=>go('main')}/>;
  if(profileSubView==='edit_profile')return <ProfileEditor userProfile={userProfile} tempProfile={tempProfile} setTempProfile={setTempProfile} onBack={()=>go('main')} onSave={saveProfile} profileUploading={profileUploading}/>;
  if(profileSubView==='help')return <Support currentUser={actualUser} onBack={()=>go('main')}/>;
  if(profileSubView==='language')return <LanguageView onBack={()=>go('main')} i18n={i18n}/>;
  if(profileSubView==='theme')return <ThemeView onBack={()=>go('main')} themeMode={themeMode} setThemeMode={setThemeMode}/>;
  if(profileSubView==='security')return <SecurityView onBack={()=>go('main')} handleLogout={handleLogout}/>;
  if(profileSubView==='legal')return <LegalView onBack={()=>go('main')}/>;
  if(profileSubView==='about')return <AboutView onBack={()=>go('main')}/>;
  if(profileSubView==='notification_preferences')return <div className="pb-24"><Header title="Notificações" onBack={()=>go('main')}/><div className="p-4">{notifLoading?<p className="py-10 text-center text-sm text-gray-400">A carregar...</p>:<div className="bg-white rounded-2xl border border-gray-100">{[['order_notifications','Pedidos'],['offer_notifications','Ofertas e promoções'],['payment_notifications','Pagamentos'],['delivery_status_notifications','Estado da entrega']].map(([key,label])=><label key={key} className="flex items-center justify-between px-4 py-4 border-b last:border-0 border-gray-100"><span className="text-sm font-semibold">{label}</span><input type="checkbox" checked={Boolean(notif[key])} onChange={e=>saveNotif({...notif,[key]:e.target.checked})}/></label>)}</div>}{notifMessage&&<p className="text-xs text-violet-700 mt-3">{notifMessage}</p>}</div></div>;

  return <div className="p-4 min-h-screen pb-24 bg-gray-50 text-left">
    <div className="bg-white rounded-3xl border border-gray-100 shadow-sm p-5"><div className="flex items-center gap-4"><div className="w-20 h-20 rounded-full overflow-hidden bg-violet-100 shrink-0"><img src={userProfile?.image||`https://ui-avatars.com/api/?name=${encodeURIComponent(userProfile?.name||'Pedejá')}&background=34205f&color=fff&size=96`} alt="Foto de perfil" className="w-full h-full object-cover"/></div><div className="min-w-0"><h1 className="text-xl font-black truncate">{userProfile?.name||'Cliente Pedejá'}</h1><p className="text-sm text-gray-500 mt-1">{userProfile?.phone||'Telefone não disponível'}</p><p className="text-sm text-gray-500 truncate">{userProfile?.email||currentUser?.email||'Email não disponível'}</p></div></div></div>
    <Section title="A minha conta"><Row icon={UserRound} title="Dados pessoais" onClick={()=>{setTempProfile({...userProfile});go('edit_profile')}}/><Row icon={MapPin} title="Moradas" onClick={()=>go('addresses')}/></Section>
    <Section title="Pagamentos"><Row icon={Banknote} title="Dinheiro" onClick={()=>{}}/><Row icon={CardIcon} title="Cartão" onClick={()=>{}}/><Row icon={WalletCards} title="Carteira" onClick={()=>go('wallet')}/></Section>
    <Section title="Preferências"><Row icon={Bell} title="Notificações" onClick={()=>go('notification_preferences')}/><Row icon={Globe2} title="Idioma" onClick={()=>go('language')}/><Row icon={Sun} title="Tema" onClick={()=>go('theme')}/></Section>
    <Section title="Segurança"><Row icon={ShieldCheck} title="Segurança" onClick={()=>go('security')}/></Section>
    <Section title="Suporte"><Row icon={CircleHelp} title="Ajuda" onClick={()=>go('help')}/><Row icon={Headphones} title="WhatsApp" onClick={()=>go('help')}/></Section>
    <Section title="Termos"><Row icon={BookOpen} title="Termos de utilização" onClick={()=>go('legal')}/><Row icon={BookOpen} title="Política de privacidade" onClick={()=>go('legal')}/><Row icon={Package} title="Política de envio" onClick={()=>go('legal')}/><Row icon={WalletCards} title="Reembolsos" onClick={()=>go('legal')}/></Section>
    <Section title="Sobre o Pedejá"><Row icon={Info} title="O que é Pedejá?" onClick={()=>go('about')}/><Row icon={Info} title="Como o Pedejá me beneficia?" onClick={()=>go('about')}/><Row icon={Info} title="Informação da empresa" onClick={()=>go('about')}/><Row icon={MapPin} title="Contacto e endereço físico" onClick={()=>go('about')}/></Section>
    <Section title="Conta"><Row icon={LogOut} title="Sair" onClick={handleLogout} danger/><Row icon={Trash2} title="Apagar a minha conta" onClick={()=>{setDeleteMessage('');setDeleteOpen(true)}} danger/></Section>
    <div className="px-1 mt-5 text-left"><p className="font-black">Pedejá</p><p className="text-xs text-gray-400 mt-1">v{packageJson.version}</p></div>
    {deleteOpen&&<div className="fixed inset-0 z-[100] bg-black/40 flex items-center justify-center p-5"><div className="bg-white rounded-2xl p-5 max-w-sm w-full"><h2 className="font-black text-lg">Apagar a minha conta</h2><p className="text-sm text-gray-600 mt-3">O pedido de eliminação será validado pelo Pedejá. Dados necessários para obrigações legais, financeiras ou operacionais podem ter de ser retidos.</p>{deleteMessage&&<p className="text-xs text-red-600 bg-red-50 rounded-xl p-3 mt-3">{deleteMessage}</p>}<div className="grid grid-cols-2 gap-2 mt-5"><button onClick={()=>setDeleteOpen(false)} className="py-3 rounded-xl bg-gray-100 font-bold">Voltar</button><button onClick={requestDelete} className="py-3 rounded-xl bg-red-600 text-white font-bold">Confirmar</button></div></div></div>}
  </div>;
}
